version: "3.9"

volumes:
  database:
    driver: local

services:
#  db:
#    build: development/db
#    ports:
#      - "15432:5432"
#    environment:
#      - "POSTGRES_USER=postgres"
#      - "POSTGRES_PASSWORD=pw4postgres"
#      - "DB_APP_NAME=bar-api"
#      - "DB_APP_USER=bar-api-user"
#      - "DB_APP_PASS=bar-api-user-password"
#    volumes:
#      - "./development/data:/var/data/db"
  postgres-db:
    image: postgres:latest
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: bartap-user
      POSTGRES_PASSWORD: bartap-user-password
      POSTGRES_DB: bartap-shared
    volumes:
      - database:/var/lib/postgresql/data