name: Bartap Java CI pipeline ;)
on:
  push:
    branches:
      - 'master'
      - 'development'
      - 'feature/2.0'
  pull_request:
    branches:
      - 'master'
      - 'development'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify "-Dspring.profiles.active=ci"

      - name: JaCoCo Report
        uses: Madrapps/jacoco-report@v1.2
        with:
          paths: ${{github.workspace}}**/surefire-reports/**/*.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          title: JaCoCo Test Coverage
          min-coverage-overall: 50
          min-coverage-changed-files: 50

      - name: JaCoCo Code Coverage Report
        uses: PavanMudigonda/jacoco-reporter@v4.5
        with:
          coverage_results_path: ${{ github.workspace }}/surefire-reports/*.xml
          coverage_report_name: Coverage
          coverage_report_title: JaCoCo
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_check_run: false
          minimum_coverage: 80
          fail_below_threshold: false
          publish_only_summary: true

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.39
        if: always()
        with:
          files: "**/surefire-reports/**/*.xml"
          check_name: Test Results